name: Auto Create PR from Dev to Master

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create PR from dev to master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if a PR already exists from dev to master
          PR_EXISTS=$(gh pr list --base master --head dev --state open --json number --jq '.[0].number')

          if [ -z "$PR_EXISTS" ]; then
            gh pr create \
              --base master \
              --head dev \
              --title "Auto PR: Merge dev into master" \
              --body "This PR merges the changes from the dev branch into master."
          else
            echo "A PR from dev to master already exists (PR #$PR_EXISTS)."
          fi
